# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7baa8ce0130fb3bd08ea59c5fcc824bf79b9f70ef5f099eef163d351484476f76b7ff4621af7a4355c5c6f6d8c75b76966e913396d9ab2579ed8f99dfd77f7d

test:
  secret_key_base: 2d833b0898bc6ca4b5fea2822a76fba973960256ef1c632e84c6c5d3117a3376f40805732209c20b99281f8cc54b1816528ea631cc28fe3df01e5f57e509257f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
